service:
  name: pwa-creator-proxy

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10

functions:
  getSlides:
    handler: handler.getSlides
    events:
      - http:
          method: get
          path: getSlides
